
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftTIMESDIVIDECONCATENATE DIVIDE ENTRADA EQUALS ESCREVER EXCLAMATION_MARK ID LPAREN MINUS NUMBER PLUS QUESTION_MARK RPAREN SEMICOLON STRING TIMESprogram : statement_liststatement_list : statement\n                      | statement_list statementstatement : assignment SEMICOLON\n                 | escrever SEMICOLON\n                 | entrada SEMICOLONassignment : ID EQUALS expressionescrever : ESCREVER expressionentrada : ENTRADA LPAREN expression RPARENexpression : expression PLUS expression\n                  | expression MINUS expression\n                  | expression TIMES expression\n                  | expression DIVIDE expressionexpression : LPAREN expression RPARENexpression : NUMBERexpression : ID\n                  | ID EXCLAMATION_MARK\n                  | ID QUESTION_MARKexpression : STRINGexpression : expression CONCATENATE expression'
    
_lr_action_items = {'ID':([0,2,3,8,10,11,12,13,14,16,20,22,23,24,25,26,],[7,7,-2,18,-3,-4,-5,-6,18,18,18,18,18,18,18,18,]),'ESCREVER':([0,2,3,10,11,12,13,],[8,8,-2,-3,-4,-5,-6,]),'ENTRADA':([0,2,3,10,11,12,13,],[9,9,-2,-3,-4,-5,-6,]),'$end':([1,2,3,10,11,12,13,],[0,-1,-2,-3,-4,-5,-6,]),'SEMICOLON':([4,5,6,15,17,18,19,21,28,29,31,32,33,34,35,36,37,],[11,12,13,-8,-15,-16,-19,-7,-17,-18,-10,-11,-12,-13,-20,-14,-9,]),'EQUALS':([7,],[14,]),'LPAREN':([8,9,14,16,20,22,23,24,25,26,],[16,20,16,16,16,16,16,16,16,16,]),'NUMBER':([8,14,16,20,22,23,24,25,26,],[17,17,17,17,17,17,17,17,17,]),'STRING':([8,14,16,20,22,23,24,25,26,],[19,19,19,19,19,19,19,19,19,]),'PLUS':([15,17,18,19,21,27,28,29,30,31,32,33,34,35,36,],[22,-15,-16,-19,22,22,-17,-18,22,-10,-11,-12,-13,22,-14,]),'MINUS':([15,17,18,19,21,27,28,29,30,31,32,33,34,35,36,],[23,-15,-16,-19,23,23,-17,-18,23,-10,-11,-12,-13,23,-14,]),'TIMES':([15,17,18,19,21,27,28,29,30,31,32,33,34,35,36,],[24,-15,-16,-19,24,24,-17,-18,24,24,24,-12,-13,24,-14,]),'DIVIDE':([15,17,18,19,21,27,28,29,30,31,32,33,34,35,36,],[25,-15,-16,-19,25,25,-17,-18,25,25,25,-12,-13,25,-14,]),'CONCATENATE':([15,17,18,19,21,27,28,29,30,31,32,33,34,35,36,],[26,-15,-16,-19,26,26,-17,-18,26,-10,-11,-12,-13,26,-14,]),'RPAREN':([17,18,19,27,28,29,30,31,32,33,34,35,36,],[-15,-16,-19,36,-17,-18,37,-10,-11,-12,-13,-20,-14,]),'EXCLAMATION_MARK':([18,],[28,]),'QUESTION_MARK':([18,],[29,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'statement_list':([0,],[2,]),'statement':([0,2,],[3,10,]),'assignment':([0,2,],[4,4,]),'escrever':([0,2,],[5,5,]),'entrada':([0,2,],[6,6,]),'expression':([8,14,16,20,22,23,24,25,26,],[15,21,27,30,31,32,33,34,35,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> statement_list','program',1,'p_program','reconhecedor_sintatico.py',15),
  ('statement_list -> statement','statement_list',1,'p_statement_list','reconhecedor_sintatico.py',19),
  ('statement_list -> statement_list statement','statement_list',2,'p_statement_list','reconhecedor_sintatico.py',20),
  ('statement -> assignment SEMICOLON','statement',2,'p_statement','reconhecedor_sintatico.py',27),
  ('statement -> escrever SEMICOLON','statement',2,'p_statement','reconhecedor_sintatico.py',28),
  ('statement -> entrada SEMICOLON','statement',2,'p_statement','reconhecedor_sintatico.py',29),
  ('assignment -> ID EQUALS expression','assignment',3,'p_assignment','reconhecedor_sintatico.py',33),
  ('escrever -> ESCREVER expression','escrever',2,'p_escrever','reconhecedor_sintatico.py',37),
  ('entrada -> ENTRADA LPAREN expression RPAREN','entrada',4,'p_entrada','reconhecedor_sintatico.py',41),
  ('expression -> expression PLUS expression','expression',3,'p_expression_binop','reconhecedor_sintatico.py',46),
  ('expression -> expression MINUS expression','expression',3,'p_expression_binop','reconhecedor_sintatico.py',47),
  ('expression -> expression TIMES expression','expression',3,'p_expression_binop','reconhecedor_sintatico.py',48),
  ('expression -> expression DIVIDE expression','expression',3,'p_expression_binop','reconhecedor_sintatico.py',49),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','reconhecedor_sintatico.py',53),
  ('expression -> NUMBER','expression',1,'p_expression_number','reconhecedor_sintatico.py',57),
  ('expression -> ID','expression',1,'p_expression_id','reconhecedor_sintatico.py',61),
  ('expression -> ID EXCLAMATION_MARK','expression',2,'p_expression_id','reconhecedor_sintatico.py',62),
  ('expression -> ID QUESTION_MARK','expression',2,'p_expression_id','reconhecedor_sintatico.py',63),
  ('expression -> STRING','expression',1,'p_expression_string','reconhecedor_sintatico.py',67),
  ('expression -> expression CONCATENATE expression','expression',3,'p_expression_concatenate','reconhecedor_sintatico.py',71),
]
